services:
  - type: web
    name: ghostzzz-uno-client
    env: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
